name: Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        override: true
        components: clippy, rustfmt

    - name: Install Trunk
      uses: jetli/trunk-action@v0.1.0

    - name: Set Rust Target
      run: rustup target add wasm32-unknown-unknown

    - name: Build with Trunk
      run: trunk build --release --verbose
      working-directory: ./dashboard

    - name: Run Dashboard
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: dist
